#!/bin/sh

## hyphop ##

. ./,config

path=../toolchain-arm_cortex-a9.neon_gcc-5.3.0_musl-1.1.15_eabi/bin
path=../toolchain-arm_cortex-a8.vfpv3_gcc-5.3.0_musl-1.1.16_eabi/bin
path=../tc/bin

pref=arm-openwrt-linux-

#export STAGING_DIR=$PWD/$path
export STAGING_DIR=$path

#export PATH="$PATH:$STAGING_DIR"

export TARGET_CROSS="$STAGING_DIR/$pref"
export ARCH=arm
export CROSS_COMPILE=$pref

echo "[i] build miZy FFMPEG arm"

[ -d $pkg_dir ] || {
echo "[e] not found $pkg_dir"
echo "[i] ./prepare - at first"
exit 1
}

export PKG_INSTALL_DIR=/tmp/ffmpeg-arm

. ./ff_config_audio_video_pulse

p=$PWD
cd $pkg_dir

#export PKG_CONFIG_PATH="/tmp/zero_builder/extra"
#PKG_CONFIG_PATH="/tmp/zero_builder/extra" \

pre=..
pre=/tmp/zero_builder
#FFMPEG_CONFIGURATION=NULL \
./configure \
--enable-cross-compile \
--cross-prefix="$TARGET_CROSS" \
--arch="$ARCH" \
--target-os=linux \
--enable-hardcoded-tables \
--extra-cflags="-I$pre/extra/include" \
--extra-ldflags="-L$pre/extra/lib -L$pre/extra/lib/pulseaudio -lcap -lwrap -lsndfile -lpulsecommon-11.1" \
--pkgconfigdir="$pre/extra/lib/pkgconfig" \
--pkg-config="pkg-config" \
--prefix="/usr" \
$ffconfig \
--enable-libpulse \
--enable-shared \
--disable-static \
--extra-version=miZy

cp config.h config.h2
VARIANT=AVL-pulse $p/remove_ffconfig_info config.h2  > config.h

#exit 

cd $p

./BUILD_FFMPEG "$@"

