#!/bin/sh

## hyphop ##

. ./,config

path=../toolchain-arm_cortex-a9.neon_gcc-5.3.0_musl-1.1.15_eabi/bin
path=../toolchain-arm_cortex-a8.vfpv3_gcc-5.3.0_musl-1.1.16_eabi/bin
path=../tc/bin

pref=arm-openwrt-linux-

#export STAGING_DIR=$PWD/$path
export STAGING_DIR=$path

#export PATH="$PATH:$STAGING_DIR"

export TARGET_CROSS="$STAGING_DIR/$pref"
export ARCH=arm
export CROSS_COMPILE=$pref

echo "[i] build miZy FFMPEG arm"

[ -d $pkg_dir ] || {
echo "[e] not found $pkg_dir"
echo "[i] ./prepare - at first"
exit 1
}

export PKG_INSTALL_DIR=/tmp/ffmpeg-arm

. ./ff_config_audio

p=$PWD
cd $pkg_dir

./configure \
--enable-cross-compile \
--cross-prefix="$TARGET_CROSS" \
--arch="$ARCH" \
--target-os=linux \
--extra-cflags="-I../extra/include" \
--extra-ldflags="-L../extra/lib" \
--prefix="/usr" \
--pkg-config="pkg-config" \
$ffconfig \
--enable-shared \
--disable-static 

cd $p

./BUILD_FFMPEG

