#!/bin/sh

## hyphop ##

ffconfig="$ffconfig\
--disable-all \
--disable-armv5te \
--disable-armv6 \
--disable-armv6t2 \
--disable-debug \
--disable-decoders \
--disable-demuxers \
--disable-doc \
--disable-encoders \
--disable-everything \
--disable-fast-unaligned \
--disable-filters \
--disable-iconv \
--disable-indevs \
--disable-libxcb \
--disable-muxers \
--disable-outdevs \
--disable-parsers \
--disable-postproc \
--disable-runtime-cpudetect \
--disable-swscale \
--disable-symver \
--disable-zlib \
--enable-decoder=aac,ac3,alac,opus,ape,flac,mp1,mp2,mp3,mpc7,mpc8,tta,vorbis,wavpack,wmav1,wmav2,pcm_*,dca,dsd*,dst \
--enable-demuxer=aac,ac3,ape,asf,flac,mp3,mpc,mov,mpc8,ogg,tta,wav,wv,rtsp,dts,dsf,dst,iff \
--enable-encoder=pcm_*,opus,flac \
--enable-filter=aresample,volume,replaygain,pan,afade,adelay,sine,anoisesrc,acrossfade,aeval,aevalsrc,join \
--enable-indev=alsa,lavfi \
--enable-muxer=null,wav,pcm_*,ffmetadata,tee,flac,ogg,oga,opus \
--enable-nonfree \
--enable-outdev=alsa \
--enable-parser=aac,ac3,mpegaudio \
--disable-protocols \
--enable-protocol=file,pipe,http,tcp,udp,rtp \
--enable-pthreads \
--enable-rdft \
--enable-small \
--enable-avcodec \
--enable-avfilter \
--enable-avformat \
--enable-ffmpeg \
--enable-avdevice \
--enable-swresample \
--disable-xlib \
"